name: otbr-gadget
type: gadget
base: core22
version: test
summary: OpenThread Border Router Gadget
description: Custom gadget to configure the OpenThread Border Router snap

architectures:
  - build-on: [amd64]

grade: stable
confinement: strict

parts:
  gadget:
    plugin: nil
    stage-snaps:
      - pc/22
