name: Markdown style checks

on:
  push:
    branches:
    - main
    paths:
    - 'docs/**'   # Only run on changes to the docs directory
  pull_request:
    branches:
    - '*'
    paths:
    - 'docs/**'   # Only run on changes to the docs directory

jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        config: "docs/.sphinx/.markdownlint.json"
        globs: |
          README.md
          CHANGELOG.md
          docs/*.md
