# This workflow tests the Sphinx Stack.
# Don't run this workflow on any repos that use the Sphinx Stack.

name: Test Sphinx Stack

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-docs:
    name: Test on docs directory
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Build docs
      run: cd docs && ./sp build html
    - name: Run style and spelling check
      if: success() || failure()
      run: cd docs && ./sp check style
    - name: Run link check
      if: success() || failure()
      run: cd docs && ./sp check links
    - name: Run Markdown style check
      if: success() || failure()
      run: cd docs && ./sp check markdown
    - name: Clean up
      if: success() || failure()
      run: cd docs && ./sp clean
